### ISSUE TITLE
Not detecting subtune correctly

### ISSUE THREAD

**Issue by knight-ryu12** [cmatsuoka/xmp-cli#7]
Problem foubd on this Scream Tracker 3 tune

[http://modarchive.org/index.php?request=view_by_moduleid&query=59854](url)
It has 3 Submodule. (confirmed in Schismtracker)
but it detected 2only.

**Comment by cmatsuoka** [comment]
Actually a library error, answered in https://github.com/cmatsuoka/libxmp/issues/51.
